config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eve.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eve/urls.py
from django.urls import path
from django.views.generic import TemplateView

from eve.views import DeckList, MatchList

app_name = 'eve'
urlpatterns = [
    path('', TemplateView.as_view(template_name='eve/rules.html'), name='index'),
    path('decks/', DeckList.as_view(), name='decks'),
    path('matches/', MatchList.as_view(), name='matches'),
    path('stats/', TemplateView.as_view(template_name='eve/stats.html'), name='stats'),
]

eve/models.py
from itertools import chain

from django.db import models
from django.utils.datetime_safe import date


class Deck(models.Model):
    name = models.CharField(max_length=256)
    year = models.PositiveSmallIntegerField(blank=True, null=True)
    aetherhub_id = models.PositiveIntegerField()

    game_wins = models.PositiveIntegerField(default=0)
    game_losses = models.PositiveIntegerField(default=0)
    game_draws = models.PositiveIntegerField(default=0)

    match_wins = models.PositiveIntegerField(default=0)
    match_losses = models.PositiveIntegerField(default=0)

    matches_2_1 = models.PositiveIntegerField(default=0)
    matches_2_0 = models.PositiveIntegerField(default=0)
    matches_1_2 = models.PositiveIntegerField(default=0)
    matches_0_2 = models.PositiveIntegerField(default=0)
    matches_rest = models.PositiveIntegerField(default=0)

    win_loss_ratio = models.FloatField(default=0.0)

    image_url = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        if self.year is None:
            return f'{self.name} ({self.game_wins}--{self.game_losses}--{self.game_draws})'
        return f'{self.name} {self.year}  ({self.game_wins}--{self.game_losses}--{self.game_draws})'

    def aetherhub_url(self) -> str:
        return f'https://aetherhub.com/Deck/Public/{self.aetherhub_id}'

    def refresh_wins_losses_draws(self, save=True) -> None:
        matches = list(chain(self.first_matches.all(), self.second_matches.all()))
        self.game_wins = 0
        self.game_losses = 0
        self.game_draws = 0
        self.match_wins = 0
        self.match_losses = 0
        self.matches_2_1 = 0
        self.matches_2_0 = 0
        self.matches_1_2 = 0
        self.matches_0_2 = 0
        self.matches_rest = 0

        for match in matches:
            if match.first_deck == self:
                wins = match.first_wins
                losses = match.second_wins
            else:
                wins = match.second_wins
                losses = match.first_wins

            self.game_wins += wins
            self.game_losses += losses
            self.game_draws += match.draws

            if wins > losses:
                self.match_wins += 1
            elif wins < losses:
                self.match_losses += 1

            if wins == 2 and losses == 0:
                self.matches_2_0 += 1
            elif wins == 2 and losses == 1:
                self.matches_2_1 += 1
            elif wins == 1 and losses == 2:
                self.matches_1_2 += 1
            elif wins == 0 and losses == 2:
                self.matches_0_2 += 1
            else:
                self.matches_rest += 1

        if self.match_wins + self.match_losses + self.game_draws == 0:
            self.win_loss_ratio = 0.0
        else:
            self.win_loss_ratio = (self.match_wins + self.game_draws / 2) / (self.match_wins + self.game_draws + self.match_losses)

        if save:
            self.save()


class Player(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Match(models.Model):
    first_player = models.ForeignKey(
        Player,
        related_name='+',
        null=True,
        blank=True,
        on_delete=models.SET_NULL, )

    second_player = models.ForeignKey(
        Player,
        related_name='+',
        null=True,
        blank=True,
        on_delete=models.SET_NULL, )

    first_deck = models.ForeignKey(
        Deck,
        related_name='first_matches',
        on_delete=models.PROTECT)

    second_deck = models.ForeignKey(
        Deck,
        related_name='second_matches',
        on_delete=models.PROTECT)

    first_wins = models.PositiveSmallIntegerField(default=0)
    second_wins = models.PositiveSmallIntegerField(default=0)
    draws = models.PositiveSmallIntegerField(default=0)

    created = models.DateField(
        default=date.today,
        editable=True,
    )

    class Meta:
        verbose_name_plural = "matches"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)

        self.first_deck.refresh_wins_losses_draws()
        self.second_deck.refresh_wins_losses_draws()

    def __str__(self):
        return f'{self.first_deck.name} [{self.first_wins} : {self.second_wins}] {self.second_deck.name} ({self.first_player} vs {self.second_player})'

eve/views.py
from django.views.generic import ListView

from eve.models import Deck, Match


class DeckList(ListView):
    model = Deck


class MatchList(ListView):
    model = Match
    queryset = Match.objects.select_related('first_deck', 'second_deck', 'first_player', 'second_player')

eve/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} | MtG&trade; EVE</title>

    <!-- Custom fonts for this template-->
    <script src="//kit.fontawesome.com/633a42c641.js" crossorigin="anonymous"></script>
    <link href="//fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'eve/css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="//cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet">

    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'eve/favicon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'eve/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'eve/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'eve/favicon-16x16.png' %}">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'eve:index' %}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">MtG&trade; EVE</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        {% with request.resolver_match.view_name as view_name %}
            <!-- Nav Item - Dashboard -->
            <li class="nav-item{% if view_name == 'eve:index' %} active{% endif %}">
                <a class="nav-link" href="{% url 'eve:index' %}">
                    <i class="fas fa-fw fa-book"></i><span>Rules</span></a>
            </li>
            <li class="nav-item{% if view_name == 'eve:decks' %} active{% endif %}">
                <a class="nav-link" href="{% url 'eve:decks' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i><span>Decks</span></a>
            </li>
            <li class="nav-item{% if view_name == 'eve:matches' %} active{% endif %}">
                <a class="nav-link" href="{% url 'eve:matches' %}">
                    <i class="fas fa-fw fa-gamepad"></i><span>Matches</span>
                </a>
            </li>
            <li class="nav-item{% if view_name == 'eve:stats' %} active{% endif %}">
                <a class="nav-link" href="{% url 'eve:stats' %}">
                    <i class="fas fa-fw fa-chart-area"></i><span>Stats</span>
                </a>
            </li>
        {% endwith %}

        <!-- Divider -->
        <hr class="sidebar-divider">


        <li class="nav-item{% if view_name == 'eve:games' %} active{% endif %}">
            <a class="nav-link" href="mailto:mtg.eve@gmail.com">
                <i class="fas fa-envelope"></i><span>Contact</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0 text-gray-500" id="sidebarToggle">
                <i class="fas fa-angle-left"></i>
                <i class="fas fa-angle-right"></i>
            </button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">
            <nav class="navbar navbar-expand navbar-light bg-white  mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <div class="d-none d-md-block">
                    <h1>Magic the Gathering: II.V format (EVE)</h1>

                    <p>Play any Type II (Standard) deck from across whole MtG™ timeline!</p>
                </div>
                <div class="d-md-none">
                    <h1>MtG: EVE</h1>
                </div>
            </nav>


            <div class="container-fluid mt-4">
                {% block content %}


                {% endblock %}
            </div>

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; MtG&trade; EVE 2020</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


<!-- Bootstrap core JavaScript-->
<script src="//code.jquery.com/jquery-3.4.1.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'eve/js/sb-admin-2.js' %}"></script>
<script src="//cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

{% block javascript %}{% endblock %}

</body>

</html>

eve/templates/eve/deck_list.html
{% extends "base.html" %}

{% load eve_filters %}

{% block title %}Decks{% endblock %}

{% block content %}
    <h2>Decks</h2>

    <div class="row">
        {% for deck in object_list %}
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="font-weight-bold text-primary text-uppercase mb-1">
                                    <a href="{{ deck.aetherhub_url }}">{{ deck.name }}</a>
                                    {% if deck.year %}
                                        <small><code>{{ deck.year }}</code></small>
                                    {% endif %}
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="mb-0 mr-3 font-weight-bold text-gray-800">{{ deck.win_loss_ratio|percent }}%</div>
                                    </div>
                                    <div class="col">
                                        <div class="progress progress-sm mr-2">
                                            <div
                                                    class="progress-bar {% if deck.win_loss_ratio > 0.7 %}bg-success{% elif deck.win_loss_ratio < 0.3 %}bg-danger{% elif deck.win_loss_ratio < 0.4 %}bg-warning{% endif %}"
                                                    role="progressbar"
                                                    style="width: {{ deck.win_loss_ratio|percent }}%"></div>
                                        </div>
                                    </div>
                                    <div class="mb-0 ml-1 font-weight-bold text-gray-800">
                                        {{ deck.game_wins }}&ndash;{{ deck.game_losses }}&ndash;{{ deck.game_draws }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        {% if deck.image_url %}
                                            <a href="{{ deck.aetherhub_url }}">
                                                <img class="img-fluid img-thumbnail w-100" src="{{ deck.image_url }}" alt="[ DECK IMG ]">
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="col">
                                        <canvas class="w-100" id="pie-deck-{{ deck.id }}"></canvas>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        {% for deck in object_list %}
            new Chart(document.getElementById('pie-deck-{{ deck.id }}').getContext('2d'), {
                type: 'doughnut',
                data: {
                    datasets: [{
                        data: [{{ deck.matches_2_0 }}, {{ deck.matches_2_1 }}, {{ deck.matches_1_2 }}, {{ deck.matches_0_2 }}, {{ deck.matches_rest }}],
                        backgroundColor: ["#1cc88a", "#a0c858", "#e79536", '#e74a3b', '#858796'],
                    }],
                    labels: [
                        '2:0s',
                        '2:1s',
                        '1:2s',
                        '0:2s',
                        'rest',
                    ],
                },
                options: {
                    legend: {
                        display: false
                    }
                }
            });
        {% endfor %}
    </script>
{% endblock %}

eve/templates/eve/match_list.html
{% extends "base.html" %}

{% load eve_filters %}

{% block title %}Matches{% endblock %}

{% block content %}
    <h2>Matches</h2>

    <table class="table table-bordered data-table">
        <thead>
        <tr>
            <th>Date</th>
            <th>First Player</th>
            <th>Second Player</th>
            <th>First Deck</th>
            <th>Second Deck</th>
            <th>Win&ndash;Loss&ndash;Draw</th>
        </tr>
        </thead>
        <tbody>
        {% for match in object_list %}
            <tr>
                <td data-order="{{ match.created|date:"U" }}">{{ match.created }}</td>
                <td>{{ match.first_player | default_if_none:"&mdash;" }}</td>
                <td>{{ match.second_player | default_if_none:"&mdash;" }}</td>
                <td>
                    {{ match.first_deck.name }}
                    {% if match.first_deck.year %}
                        <code>{{ match.first_deck.year }}</code>
                    {% endif %}
                </td>
                <td>
                    {{ match.second_deck.name }}
                    {% if match.second_deck.year %}
                        <code>{{ match.second_deck.year }}</code>
                    {% endif %}
                </td>
                <td>
                    {{ match.first_wins }}&ndash;{{ match.second_wins }}&ndash;{{ match.draws }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.data-table').DataTable();
        });
    </script>
{% endblock %}

eve/templates/eve/stats.html
{% extends "base.html" %}

{% load eve_filters %}

{% block title %}Matches{% endblock %}

{% block content %}
    <h2>Stas</h2>

    <p>... are comming soon&trade;</p>

{% endblock %}